use_frameworks!

platform :ios, '8.0'

target 'FIPPod_BaiduIDCard_Example' do
  pod 'FIPPod_BaiduIDCard', :path => '../'

  target 'FIPPod_BaiduIDCard_Tests' do
    inherit! :search_paths

    
  end
end
